name: eecs442
channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=5_kmp_llvm
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - absl-py=2.3.1=pyhd8ed1ab_0
  - addict=2.4.0=pyhd8ed1ab_3
  - aom=3.12.1=h7934f7d_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py310hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_0
  - charset-normalizer=3.4.4=py310h06a4308_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - dav1d=1.2.1=h5eee18b_0
  - einops=0.8.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.14.1=ha770c72_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gettext=0.21.0=hedfda30_2
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.5=h71b1129_1002
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.62.2=py310h1b8f574_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h5py=3.14.0=py310he0d80d8_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py310h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.83.1=hb768ceb_6
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.16.0=heebcbe5_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.24=h86f0d12_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h767d61c_7
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libjpeg-turbo=3.1.1=hb25bd0a_0
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h27cfd23_1
  - libopenjpeg=2.5.4=hee96239_0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=4.25.3=he621ea3_0
  - libre2-11=2024.02.01=h2f2cdcf_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h8261f1e_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.9=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2023.2.0=ha770c72_50498
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py310hb6b6513_0
  - mpich=4.1.1=hbae89fd_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.4.1=hbb512f6_0
  - networkx=3.4.2=py310h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h4e0627c_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py310h80abafc_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plyfile=1.1=pyhd8ed1ab_0
  - protobuf=4.25.3=py310he36ed58_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - pytorch=2.3.1=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cluster=1.6.3=py310_torch_2.3.0_cu121
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py310_torch_2.3.0_cu121
  - pytorch-sparse=0.6.18=py310_torch_2.3.0_cu121
  - pyyaml=6.0.2=py310h5eee18b_0
  - re2=2024.02.01=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - scipy=1.15.2=py310h1d65ade_0
  - sharedarray=3.2.4=py310hf779ad0_3
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.14.0=py310h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.13.0=hb60516a_3
  - tbb-devel=2021.13.0=h74b38a2_3
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310hed992bd_3
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - termcolor=3.2.0=pyhd8ed1ab_0
  - tesseract=5.5.1=hea8d43c_1
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.3.0=pyhcf101f3_0
  - torchaudio=2.3.1=py310_cu121
  - torchtriton=2.3.1=py310
  - torchvision=0.18.1=py310_cu121
  - typing_extensions=4.15.0=py310h06a4308_0
  - urllib3=2.5.0=py310h06a4308_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.43.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - abnf==2.2.0
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - backoff==2.2.1
      - blinker==1.9.0
      - cachetools==6.2.2
      - ccimport==0.4.4
      - chardet==5.2.0
      - cint==1.0.0
      - click==8.3.0
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cumm-cu121==0.7.11
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - descartes==1.1.0
      - diskcache==5.6.3
      - eval-type-backport==0.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fickling==0.1.5
      - fire==0.7.1
      - flash-attn==2.5.9.post1
      - flask==3.1.2
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gql==4.0.0
      - graphql-core==3.2.7
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - intervaltree==3.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.15
      - kaitaistruct==0.11
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lightning-utilities==0.15.2
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - multidict==6.7.0
      - narwhals==2.10.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - nuscenes-devkit==1.2.0
      - open3d==0.18.0
      - opencv-python-headless==4.11.0.86
      - pandas==2.3.3
      - parameterized==0.9.0
      - parso==0.8.5
      - pccm==0.4.16
      - pdfminer-six==20250506
      - pexpect==4.9.0
      - plotly==6.3.1
      # - pointops==1.0         # IGNORE: install from source
      - polyfile-weave==0.5.7
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pycocotools==2.0.10
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.21
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2025.10.23
      - requests-toolbelt==1.0.0
      - retrying==1.4.2
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - sentry-sdk==2.45.0
      - setuptools==80.9.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - spconv-cu121==2.3.8
      - stack-data==0.6.3
      - stdlib-list==0.11.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - timm==0.9.12
      - tokenizers==0.22.1
      - torch-geometric==2.7.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==3.3.1
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - wandb==0.23.0
      - wcwidth==0.2.14
      - weave==0.52.17
      - wget==3.2
      - widgetsnbextension==4.0.14
      - xxhash==3.6.0
      - yarl==1.22.0
